services:
  quiz:
    build:
      context: '.'
      dockerfile: './Dockerfile'
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - '80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      UID: 1000
      GID: 1000
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.quiz.rule=Host(`quiz.test`)'
      - 'traefik.http.routers.quiz.entrypoints=web'
      - 'traefik.http.services.quiz.loadbalancer.server.port=80'
      - 'traefik.docker.network=sail'

networks:
  sail:
    external: true
